### ISSUE TITLE
TypeError: TesseractWorker is not a constructor

### ISSUE THREAD

**Issue by hussainhyder23** [naptha/tesseract.js#346] opened 2019-10-05 08:05 UTC
const Worker= new TesseractWorker();//For analyzing images
              ^

TypeError: TesseractWorker is not a constructor
    at Object.<anonymous> (/Users/hyder/Desktop/OCR-PDF/app.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
[nodemon] app crashed - waiting for file changes before starting...

Please suggest a solution

**Comment by jeromewu** [comment] 2019-10-05 10:46
Hi, may I know the version of tesseract.js you used?

**Comment by udithjoishi** [comment] 2019-10-06 14:23
Same problem , version 2.0.0-beta.1

**Comment by alexmorleyfinch** [comment] 2019-10-08 23:13
I have a similar problem. My package.json has:
```
    "tesseract.js": "1.0.19",
    "tesseract.js-core": "1.0.2"
```
and if I nuke node modules and the package-lock and do `npm install`, I seem to get the v2 with the updated API. This may be a problem with npm or maybe my setup. Can anybody confirm?

**Comment by jeromewu** [comment] 2019-10-08 23:24
To install v2, you need to add "next" tag in npm install

$ npm install tesseract.js@next

In the latest version (2.0.0-beta.1), TesseractWorker has deprecated and you need to use createWorker instead. Check README.md for details.

**Comment by alexmorleyfinch** [comment] 2019-10-08 23:46
I forgot to actually write my problem, sorry. I am expecting npm to install version 1 (given that my package lock points to version 1), but for some reason npm installs version 2, even if I nuke and try again, I always get version 2 when I expect version 1. Thanks

**Comment by jeromewu** [comment] 2019-10-09 00:05
Have you tried deleting package-lock.json and npm install to regenerate a new one?

**Comment by alexmorleyfinch** [comment] 2019-10-09 09:00
Yes I have tried `rm package-lock.json` and `rm -rf node_modules` and npm install and I still get the problem. I do not have it globally installed either, so not sure what's going on

**Comment by alexmorleyfinch** [comment] 2019-10-09 09:11
If, after an install I go to the package-lock.json and get the resolved url for tesseract.js, I get `https://registry.npmjs.org/tesseract.js/-/tesseract.js-1.0.19.tgz` as expected. However if I download the files from that link, I appear to get the latest code. The way I checked this was going to /dist/tesseract.js and seeing what gets exported. I got the line `module.exports = create();` which I believe is for the latest code yes?

**Comment by jeromewu** [comment] 2019-10-10 01:44
For the latest code, you can check here: https://unpkg.com/tesseract.js@2.0.0-beta.1/dist/tesseract.min.js

But I have to say the issue is not related to tesseract.js, you can check npm's github repo. here: https://github.com/npm/cli

**Comment by alexmorleyfinch** [comment] 2019-10-10 10:53
Thanks for your help. I found the solution that I needed. You can close this issue now I think as this response should fix OP's problem: I needed these specific versions in my package.json.

```
    "tesseract.js": "2.0.0-alpha.13",
    "tesseract.js-core": "2.0.0-beta.11"

```
I needed these specific versions to get the version of the API that I originally coded to. I will move over to the latest v2 when ready, but for now this worked for me. Thanks for helping.

For anyone else reading, if you are getting the error `TesseractWorker is not a constructor` and you don't have time right now to update to the latest API, then use the above versions. It will work until you get time to update your code.

The reason this was a problem for me was because I coded to `^2.0.0-alpha.13` which means that when the owner made a new release and changed the API, any new deployments I made using `npm install` would install the new API, and all my code broke (which is my fault because I had `^2` in the `package.json`). It took me a while to realise which version I originally coded to. Once you remove the `^` though, then `npm` won't automatically get the latest.

Note: You should probably update your codebase rather than linking to a specific alpha build, but until you get time to do that, this should work for you.

**Comment by jeromewu** [comment] 2019-10-10 12:00
Glad that there is a solution, close the issue for now, @hussainhyder23 feel free to reopen with more information.

**Closed by jeromewu** 2019-10-10 12:00 UTC

**Comment by exaland** [comment] 2019-12-27 19:26
@alexmorleyfinch Thanks your solution works for me 👍

**Comment by ABHISHEK-AMRUTE** [comment] 2020-01-11 15:29
@alexmorleyfinch still getting the error.

**Comment by jaskirat1313** [comment] 2020-05-30 22:15
![WhatsApp Image 2020-05-31 at 3 45 15 AM](https://user-images.githubusercontent.com/40401279/83340032-2af8fc00-a2f1-11ea-9314-6175acd86885.jpeg)

**Comment by jaskirat1313** [comment] 2020-05-30 22:16
![WhatsApp Image 2020-05-31 at 3 46 21 AM](https://user-images.githubusercontent.com/40401279/83340047-554ab980-a2f1-11ea-8452-a0546a92d2e1.jpeg)

**Comment by jaskirat1313** [comment] 2020-05-30 22:18
why i am geting this problem. i worked on latest version of tesseract.js version

**Comment by zahidalidev** [comment] 2020-08-10 00:46
i have the same issue and i resolved like this 
install package like this npm i tesseract.js@2.0.0-beta.1

and in in app.js

import { createWorker } from 'tesseract.js';

const worker = createWorker({
  logger: m => console.log(m),
});

const saveFile = async(e) => {
    e.preventDefault();
    this.setState({ocr: "Recognizing..."});
    
    await worker.load();
    await worker.loadLanguage('eng');
    await worker.initialize('eng');
    const { data: { text } } = await worker.recognize(image url);
    this.setState({ocr: text});
  }
saveFile();

**Comment by 26palak** [comment] 2021-09-29 06:03
const worker = new TesseractWorker();
               ^

TypeError: TesseractWorker is not a constructor
    at Object.<anonymous> (C:\Users\888073\hello\app.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Quickdraw19** [comment] 2021-11-24 17:28
> i have the same issue and i resolved like this install package like this npm i tesseract.js@2.0.0-beta.1
> 
> //and in in app.js file
> 
> import { createWorker } from 'tesseract.js';
> 
> const worker = createWorker({ logger: m => console.log(m), });
> 
> const convertToText = async() => { await worker.load(); await worker.loadLanguage('eng'); await worker.initialize('eng'); const { data: { text } } = await worker.recognize(image url); console.log("text from file: ", text); } convertToText();

I'm getting "SyntaxError: Cannot use import statement outside a module".

**Comment by Quickdraw19** [comment] 2021-11-24 17:33
> import { createWorker } from 'tesseract.js';
> 
> const worker = createWorker({ logger: m => console.log(m), });

I have the same problem. I installed tesseract.js@next
 "dependencies": {
    "tesseract.js": "^2.0.0-beta.2"
  },

**Comment by Aevam** [comment] 2022-01-30 13:43
createWorker is not a constructor

**Comment by Aevam** [comment] 2022-01-30 13:47
const worker = createWorker();

**Comment by Aevam** [comment] 2022-01-30 13:48
remove the new

**Comment by Aevam** [comment] 2022-01-30 13:48
replace const worker = new createWorker(); to const worker = createWorker();

**Comment by Aevam** [comment] 2022-01-30 13:48
"tesseract.js": "^2.0.0-beta.1"

**Comment by chiragksharma** [comment] 2023-04-15 13:17
> remove the new

Yeah that worked totally fine. Thanks
