### ISSUE TITLE
The numbers such as 11,22,33,44... are detecting as 1,2,3,4... also some numbers are not recognizing properly

### ISSUE THREAD

**Issue by anixsam** [naptha/tesseract.js#684] opened 2022-11-07 09:14 UTC
Tested with different images but the issue is persisting on the case of numbers. If there is numbers as 11,22,33,44... it's not detecting the ones repeating it detects as 1,2,3,4... . Also coming to some numbers such as 7,8 as misrecognized

**Comment by Balearica** [comment] 2022-11-08 20:35
Tesseract.js is the Javascript/Webassembly port of Tesseract.  We do not make any edits to the recognition engine, so any accuracy issues with the Tesseract engine are outside of the scope of this project.  If you would like to pursue further, you should (1) check whether the issue is present when using the main (CLI) [Tesseract project](https://github.com/tesseract-ocr/tesseract) and (2) if so, and you believe this constitutes a bug, raise the issue with that project.

**Comment by Balearica** [comment] 2022-11-25 20:50
Closing as the presence of recognition errors is not a bug in this project (see above).

**Closed by Balearica** 2022-11-25 20:50 UTC
Labels: recognition accuracy
