### ISSUE TITLE
Worker Script Path has 'http:/localhost' prepended, causing MODULE_NOT_FOUND error

### ISSUE THREAD

**Issue by sssanwar** [naptha/tesseract.js#474] opened 2020-08-04 12:44 UTC
**Describe the bug**
When trying to run tesseract.js in Jest for a unit test I get this error message saying it's unable to load worker-script. Upon inspection the supplied path appeared somehow has been concatenated with 'http:/localhost/'.

```
Error: Cannot find module '**/Users/myusername/Projects/my-app/http:/localhost/Users/myusername/Projects/my-app/node_modules/tesseract.js/src/worker-script/node/index.js**'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**To Reproduce**
Install tesseract.js and tesserract-core.js throught npm or yarn. I am using yarn in this case. Write a unit test in jest to load tesseract. I tried supplying the 'workerPath', it didn't seem to help. The supplied path would also have the 'localhost' string prepended to the path.

The issue does not happen when I run tesseract.js in a browser.

**Expected behavior**
The worker-script path shouldn't have been concatenated with 'http:/localhost'.

**Desktop:**
 - OS: MacOS 10.15.6
 - Node: v12.16.2
 - Tesseract.js: 2.1.1

**Comment by MaffooBristol** [comment] 2020-08-10 11:06
Same issue here on Node 14

**Comment by slonoed** [comment] 2020-10-16 04:18
Hi @sssanwar !
Did you find workaround for it?

**Comment by marcincichocki** [comment] 2021-03-20 22:23
This is strictly `jest` "issue". The error origins [here](https://github.com/naptha/tesseract.js/blob/90466c3b5504a9220ba0ff91ccec22003f72cbd2/src/utils/getEnvironment.js#L10) because tesseract tries to detect current environment by simple check `typeof window === 'object'`. Unfortunately `jest` loads `jsdom` by default which sets global `window` variable. Therefore tesseract tries to load dependencies via http.

To solve it simply set [testEnvironment](https://jestjs.io/docs/configuration#testenvironment-string) option to `node` in jest config. If you somehow rely on jsdom in your tests I suggest using:

```js
/**
 * @jest-environment node
 */
```

at the top of the affected file.

related issue: https://github.com/facebook/jest/issues/3692

**Comment by Balearica** [comment] 2022-09-17 22:47
If this issue is still active can somebody please upload a reproducible code snippet/repo that produces this error? Seems likely this can be fixed but I'm not a Jest user.

**Comment by marcincichocki** [comment] 2022-09-18 11:02
@Balearica I believe this was fixed(https://github.com/naptha/tesseract.js/pull/498) and deployed in 2.1.5.

**Comment by Balearica** [comment] 2022-09-18 17:37
@marcincichocki Thanks for confirming, closing the issue.

**Closed by Balearica** 2022-09-18 17:37 UTC
