### ISSUE TITLE
Issue with nextjs app router

### ISSUE THREAD

**Issue by Hillel-Nagid** [naptha/tesseract.js#842] opened 2023-10-17 07:20 UTC
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**
5.0.2
**Describe the bug**
I have tried to use the library in a Next.js project using route handlers. I "copy-paste"ed the expamle from the README file, and got the following error when running: uncaughtException: Error: Cannot find module '<MY WORK DIR>\.next\worker-script\node\index.js'

**To Reproduce**
`npx create-next-app@latest`
create a route handler
initialize `createWorker('eng')`
read an image buffer from file, and pass it to `worker.recognize()`

**Expected behavior**
I expected the code to run

**Device Version:**
 - OS + Version: Windows 11
 - Node version Node v19.4.0

**Comment by Balearica** [comment] 2023-10-18 20:17
It looks like several of these steps require writing code.  Please provide an example repo that can be easily cloned and run to produce this issue.

**Comment by Balearica** [comment] 2023-10-24 18:06
Closing as it's unclear if this is an issue with Tesseract.js or the specific code and/or framework at issue.  Will reopen if a reproducible example is provided.

**Closed by Balearica** 2023-10-24 18:05 UTC
