### ISSUE TITLE
Error: InvalidStateError thrown on Firefox

### ISSUE THREAD

**Issue by Kcchouette** [naptha/tesseract.js#375] opened 2019-12-20 16:20 UTC
Hello,

on your default page https://tesseract.projectnaptha.com/ with Firefox 71.0 and Firefox 72.0, I have this error:

```
Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. createWorker.js:135:12
    exports createWorker.js:135
    onmessage onMessage.js:3
uncaught exception: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
```

So we can't try the demo on your website

Cheers

**Comment by jeromewu** [comment] 2019-12-21 07:02
Hi, may I know if you are using **Private Window** in firefox? It might be the root cause of this problem as IndexedDB is not supported in private mode.

**Comment by Kcchouette** [comment] 2019-12-21 11:19
Yes I am using **Private Mode**.

**Comment by jeromewu** [comment] 2019-12-21 11:23
Then the only solution is not to use private mode, close the issue.

**Closed by jeromewu** 2019-12-21 11:23 UTC

**Comment by Kcchouette** [comment] 2019-12-21 11:27
@jeromewu Maybe you can write that something? Or deals with the exception?

**Comment by jeromewu** [comment] 2019-12-21 11:37
This issue well describes the problem and our discussion has found the solution, I believe here will help people with the same problem, no extra documentation is required.
