### ISSUE TITLE
Not seeing any results

### ISSUE THREAD

**Issue by zeke** [naptha/tesseract.js#35] opened 2016-10-15 05:49 UTC
Using the sample code provided in the readme, I'm not seeing output of any kind. The process just seems to hang.

I created a sample repo. To reproduce:

```
git clone https://github.com/zeke/ocr-test/
cd ocr-test
npm install
npm start
```

My setup:

```
❯ node -v
v6.8.1

❯ uname -a
Darwin C02R41WSFVH8 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

❯ npm ls tesseract.js
ocr-test@ /Users/zeke/Desktop/ocr-test
└── tesseract.js@1.0.7 
```

PS Out of curiosity, why is node>=6.8 required?

**Comment by bijection** [comment] 2016-10-17 03:49
Re: node versions we use `const` and `class` and stuff that only the 6.8+ supports. 
Have you tried using a smaller image? It might just be taking a long time.

**Comment by Dreamersoul** [comment] 2016-10-17 09:39
@zake the problem is with the image I have used another one and its working fine

**Comment by zeke** [comment] 2016-10-17 12:06
I just downsaved the file to 700KB and let the process run for a while. After over ten minutes, I still see no output and my CPU usage is really high.

**Comment by bijection** [comment] 2016-10-17 16:57
It seems that jpeg on node is very slow, and that perhaps the bottleneck is inter-process communication, as discussed in #53. Closing this so we can continue investigating there.

**Closed by bijection** 2016-10-17 16:57 UTC
