### ISSUE TITLE
Error: node_modules/tesseract.js/src/index.d.ts:158:69 - error TS2304: Cannot find name 'OffscreenCanvas'.

### ISSUE THREAD

**Issue by sannila** [naptha/tesseract.js#809] opened 2023-08-23 13:36 UTC
**Tesseract.js version 4.1.1**

**Describe the bug**
receiving Error: node_modules/tesseract.js/src/index.d.ts:158:69 - error TS2304: Cannot find name 'OffscreenCanvas'. when compiling the project

**To Reproduce**
1. Created an angular project (v15.0.5)
2. do **npm install tesseract.js**
3. import Tesseract from 'tesseract.js';
4. add below function, 

`Tesseract.recognize(
  'https://tesseract.projectnaptha.com/img/eng_bw.png',
  'eng',
  { logger: m => console.log(m) }
).then(({ data: { text } }) => {
  console.log(text);
})`

run the application "npm start"

Please attach any input image required to replicate this behavior.

![image](https://github.com/naptha/tesseract.js/assets/41979819/b9d73d86-1a85-4ea6-a2d0-c6ac49fa3b21)

**Expected behavior**
Should run the application

**Device Version:**
 - OS + Version: Windows 11
 - Node version [Node v18.12.1]

**Comment by Balearica** [comment] 2023-08-23 23:23
That error seems fairly literal--your project uses Typescript, and for whatever reason `OffscreenCanvas` is not a type that is defined in your project.  I'm not sure why this would not be defined by default since `OffscreenCanvas` was first released in Chrome in 2018 and is now supported in all browsers, however  you should be able to resolve simply by making sure the type is defined.  There are many resources explaining how to do this online--see e.g. https://stackoverflow.com/questions/50831981/how-to-use-offscreencanvas-in-typescript-project. 

If you are unable to resolve the issue, please link to a repo that can be run to reproduce.

**Comment by SiaStasia** [comment] 2023-08-29 09:32
same behavior here with angular V15. in my case what helped was to update typescript and add @types/offcreencanvas.

- npm i typescript
- npm i @types/offscreencanvas

to be sure no caching takes over, delete node_modules folder from your project, before installing this packages.

good luck!

**Comment by Balearica** [comment] 2023-09-14 00:14
Closing as resolved.

**Closed by Balearica** 2023-09-14 00:14 UTC

**Comment by Rubylago** [comment] 2023-12-03 09:18
@sannila in my case, after  npm i --save-dev @types/offscreencanvas, I'll have to add "OffscreenCanvas" to the `"types"` array in  `tsconfig.app.json` file to make it work. Here's an example:
```
"compilerOptions": {
    //...
    "types": ["node", "OffscreenCanvas"],
    "typeRoots": ["node_modules/@types"]
}
```
