### ISSUE TITLE
demo can't run

### ISSUE THREAD

**Issue by happy-sw** [naptha/tesseract.js#767] opened 2023-05-22 06:01 UTC
![image](https://github.com/naptha/tesseract.js/assets/62538052/b24e5741-24dc-4cc1-a94f-dd6cd2ce9ab1)

**Comment by happy-sw** [comment] 2023-05-22 06:05
Can you give me any replies? When I open the demo web page,I can't load it out!what's wrong

**Comment by Balearica** [comment] 2023-05-23 20:36
The website at [tesseract.projectnaptha.com](https://tesseract.projectnaptha.com/) seems to work fine for me, however in general that site has not been updated in several years so it will experience many bugs that have since been patched. 

In general, if you want to experiment with Tesseract.js you should use the examples in [this folder](https://github.com/naptha/tesseract.js/tree/master/examples/browser), which are actively maintained.  We should get around to updating the public site eventually to use the latest version of Tesseract.js.

**Comment by Balearica** [comment] 2023-05-28 00:46
I opened a new issue to track updating the website (see #768).  Closing this issue as it does not appear to be reproducible.

**Closed by Balearica** 2023-05-28 00:46 UTC
