### ISSUE TITLE
libpng error: read error in memio_png_read_data

### ISSUE THREAD

**Issue by CatalanNathan** [naptha/tesseract.js#661] opened 2022-09-16 23:28 UTC
**Hello, I found a problem**
```js
node:internal/event_target:916
  process.nextTick(() => { throw err; });
                           ^

Error: RuntimeError: null function or function signature mismatch
    at Worker.<anonymous> (/home/nathan/Bot discord - Copie/BOT GS/node_modules/tesseract.js/src/createWorker.js:173:15)
    at Worker.emit (node:events:520:28)
    at MessagePort.<anonymous> (node:internal/worker:232:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

# **To Reproduce**
my script : 
```js
client.on('messageCreate', (message) => {
    if (message.author.id === "1004357154205085748" && message.channelId === "963178509130424340") {
        if (message.content.includes("Liste des membres avec le rôle"))
            return;
        let i = 0;
        let split = message.content.split("\n");
        split.forEach((element) => {
            setTimeout(() => {
                let split2 = element.split(":")[0];
                if (split2 !== "```json" && split2 !== "```") {
                    message.channel.send(`s?u <@${split2}>`);
                    allListe.push(split2);
                }
            }, 10000 * i);
            i++;
        })
    }
})

client.on('messageUpdate', (oldMessage, newMessage) => {
    if (newMessage.author.id === "491769129318088714" && newMessage.channelId == "963178509130424340") {
        if (newMessage.content.includes(newMessage.id))
            return;
        let attachement = newMessage.attachments.first().url;
        downloadImage(attachement, "image.png")
        try {
            Tesseract.recognize(
                'image.png',
                'eng'
                )?.then(({ data: { text } }) => {
                    let hours = text.split("7d").slice(1).join("|").split("\n").join("|").split("|").filter((month , idx) => idx < 2);
                    if (parseInt(hours[1]) < nbHours) {
                        console.log(`<@${allListe[value]}> - ${hours[0]} - ${hours[1].replace("hours", "min")} - Retrograde`);
                        allId.push(allListe[value]);
                    } else {
                        console.log(`<@${allListe[value]}> - ${hours[0]} - ${hours[1].replace("hours", "min")} - Rank up`);
                    }
                    value++;
                })
        } catch (error) {}
    }
})
```
And for a my repo : 
```sh
$ ls 
eng.traineddata  image.png  index.js  node_modules  package.json  package-lock.json
```
And you got the same error.
I'm on the  "tesseract.js": "^3.0.2"

Thanks you so much

**Comment by Balearica** [comment] 2022-09-17 00:07
@CatalanNathan It does not look like this code snippet can be run independently.  We need a reproducible example, which means either (1) a code snippet that can be copy/pasted and run on any system [without your particular setup] or (2) a Git repo that can be easily cloned and run to produce the error.

**Comment by CatalanNathan** [comment] 2022-09-17 00:17
git@github.com:CatalanNathan/tesseract.js-libpng-error.git @Balearica Thanks you so much

**Comment by Balearica** [comment] 2022-09-17 20:18
@CatalanNathan I was unable to run the repo as it appears to require some additional setup (`Error [TOKEN_INVALID]: An invalid token was provided.`), so I ran the following snippet containing only the Tesseract.js-related part of the code (using the `image.png` file in your repo) and everything ran as expected.  Therefore, unless you are using an unsupported version of Node.js (versions >=14 are supported) I do not believe your issue is directly related to Tesseract.js. 

```
var Tesseract = require('tesseract.js');

Tesseract.recognize(
    'image.png',
    'eng'
    ).then((x) => console.log(x.data.text));
```

Skimming your code, I believe the issue is your  `downloadImage` function.  The function `Axios.get` runs asynchronously.  This means it returns immediately, before `image.png` is created, and therefore `Tesseract.recognize` is run too soon.  You should review online documentation/guides on asynchronous JavaScript concepts, as in addition to being the likely cause of this specific problem, asynchronous functions are very common/important in JavaScript.

**Comment by Balearica** [comment] 2022-10-08 23:44
Closing given that (as explained above) I do not believe this is caused by a bug in Tesseract.js.

**Closed by Balearica** 2022-10-08 23:44 UTC
