### ISSUE TITLE
Can not start debbug with webstorm

### ISSUE THREAD

**Issue by hrishynpavlo** [naptha/tesseract.js#316] opened 2019-08-03 14:50 UTC
Hello everyone can not start debugger in web storm using tesseract.js. 
The error is: "Starting inspector on 127.0.0.1:58767 failed: address already in use
events.js:174" 

Run is working correctly. Could you help me to debug?

**Comment by jeromewu** [comment] 2019-08-25 06:52
No experience in webstorm, add **help wanted** tag for now

**Comment by jeromewu** [comment] 2019-10-28 08:43
This issue was caused by the conflict of main process and child process, should be fixed in v2.0.0-beta.2

**Closed by jeromewu** 2019-10-28 08:43 UTC
Labels: help wanted
