### ISSUE TITLE
Can't handle error with corrupted picture

### ISSUE THREAD

**Issue by Koilanetroc** [naptha/tesseract.js#188] opened 2018-02-20 06:05 UTC
I'm trying to recognize a corrupted picture and getting an error, that I can't handle anyway.
```
var Tesseract = require('tesseract.js');
try {
  Tesseract.recognize('./screens/failed2.png')
    .catch(err => console.log(err));
} catch (err) {
  console.log(err)
}
```
And the error I'm getting
```
/home/oleg/trash/activator_pictures/node_modules/tesseract.js/src/node/index.js:59
                if (err) throw err;
                         ^

Error: Unexpectedly reached end of file
    at PNGReader.readBytes (/home/oleg/trash/activator_pictures/node_modules/png.js/PNGReader.js:70:9)
    at PNGReader.decodeChunk (/home/oleg/trash/activator_pictures/node_modules/png.js/PNGReader.js:113:19)
    at PNGReader.parse (/home/oleg/trash/activator_pictures/node_modules/png.js/PNGReader.js:401:20)
    at loadImage (/home/oleg/trash/activator_pictures/node_modules/tesseract.js/src/node/index.js:58:20)
    at /home/oleg/trash/activator_pictures/node_modules/tesseract.js/src/node/index.js:48:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:437:3)

```
![failed2](https://user-images.githubusercontent.com/23165188/36409514-84141370-163e-11e8-8dbc-a5cb3528c6e8.png)

**Comment by motin** [comment] 2018-10-21 09:30
This seems to be a duplicate of https://github.com/naptha/tesseract.js/issues/122

**Comment by jeromewu** [comment] 2019-10-10 05:29
A corrupted image is not an acceptable input for tesseract.js, thus cause it to crash. We don't plan to solve this, close for now.

**Closed by jeromewu** 2019-10-10 05:29 UTC
