### ISSUE TITLE
Search a specific pattern in the image

### ISSUE THREAD

**Issue by ZioTano** [naptha/tesseract.js#492] opened 2020-10-26 15:26 UTC
A regex search would be a fantastic feature.
It could allow complex search in images.
it seems that a kind of that is already present in c++ branch of the project.
https://github.com/tesseract-ocr/tesseract/blob/442b5b7/dict/trie.h#L192

**Comment by Balearica** [comment] 2022-09-22 01:29
This is blocked by #613 as it looks like this is an "init only" parameter.

**Comment by Balearica** [comment] 2022-09-24 01:55
Support for initialization parameters was added as part of #613 to the [dev/v4](https://github.com/naptha/tesseract.js/tree/dev/v4) branch, and will be released with version 4. If you would like to test before then, instructions are in https://github.com/naptha/tesseract.js/issues/662.

Regarding the user pattern feature specifically, I confirmed that this is supported using the sample image and pattern file provided in the [Tesseract documentation](https://tesseract-ocr.github.io/tessdoc/APIExample-user_patterns). 

Here is a minimal example:

```
<!DOCTYPE HTML>
<html>
  <head>
    <script src="/dist/tesseract.dev.js"></script>
  </head>
  <body>
    <input type="file" id="uploader">
    <script>
      const recognize = async function(evt){
        const files = evt.target.files;
        const worker = await Tesseract.createWorker({
          corePath: '/tesseract-core-simd.wasm.js',
          workerPath: '/dist/worker.dev.js',
          logger: function(m){console.log(m);},
          cacheMethod: 'none',
        });
        await worker.loadLanguage('eng');
        await worker.writeText("/user_patterns_file", String.raw`\A\A\d\d\d\d\A`);
        await worker.initialize('eng', undefined, "user_patterns_file /user_patterns_file");
        const ret = await worker.recognize(files[0]);
        console.log(ret.data.text);
      }
      const elm = document.getElementById('uploader');
      elm.addEventListener('change', recognize);
    </script>
  </body>
</html>
```
[Note: at the time of this writing version 4 has not released yet.  Therefore, `workerPath` and `corePath` must both be manually set to versions of those files from the `dev/v4` branch of [Tesseract.js](https://github.com/naptha/tesseract.js/tree/dev/v4) and [Tesseract.js-core](https://github.com/naptha/tesseract.js-core/tree/dev/v4), respectively.]

![user_pattern_example](https://user-images.githubusercontent.com/100809261/192075017-607527fc-ad6c-4b97-8338-7b7e0ea6751f.png)

**Comment by Balearica** [comment] 2022-11-25 20:43
Closing as this was added in [Version 4](https://github.com/naptha/tesseract.js/releases/tag/v4.0.0).

**Closed by Balearica** 2022-11-25 20:43 UTC

**Comment by jlucaso1** [comment] 2024-04-15 13:07
How i can do this in newer versions?

**Comment by Balearica** [comment] 2024-04-20 02:09
@jlucaso1 An example that works with the latest version of Tesseract (v5.0.5) is below.

```
<!DOCTYPE HTML>
<html>
  <head>
    <script src="/dist/tesseract.min.js"></script>
  </head>
  <body>
    <input type="file" id="uploader">
    <script>
      const recognize = async function(evt){
        const files = evt.target.files;
        const worker = await Tesseract.createWorker('eng', 1);

        await worker.writeText("/user_patterns_file", String.raw`\A\A\d\d\d\d\A`);
        await worker.setParameters({user_patterns_file: "/user_patterns_file"})

        await worker.reinitialize('eng', 1, {user_patterns_file: "/user_patterns_file"})

        const ret = await worker.recognize(files[0]);
        console.log(ret.data.text);
      }
      const elm = document.getElementById('uploader');
      elm.addEventListener('change', recognize);
    </script>
  </body>
</html>

```
