### ISSUE TITLE
NodeErrror: Channel Closed (for PNG), Error: write EPIPE (for JPEG)

### ISSUE THREAD

**Issue by asWater** [naptha/tesseract.js#271] opened 2019-03-05 09:23 UTC
Hello.

I've searched the same error but I could not find the one, so I am writing this issue now.

I am using Node version 10.15.1, and executed the simple example on my node application.

Tesseract.recognize(myImage)
.then(function(result){
    console.log(result)
})

As a result, I got the error as an attached image.
![nodechannelclosed](https://user-images.githubusercontent.com/10876704/53793715-c4f8ba00-3f71-11e9-9192-d68c8702646e.png)

All I have done is 
- npm install tesseract.js --save
- Set const Tesseract = require( 'tesseract.js' )
- Execute recognize method as written above by passing the image file path ("./UploadedFiles/TestFiles/test.png)

Am I missing something to use it?  

By the way, when I use the jpeg file, the following error is returned.
> Error: write EPIPE

Please help me to solve this problem.

**Comment by brdacost** [comment] 2019-04-02 22:07
I am having the exact same problem. However, when I run a test code apart from my API's main project (which is basically the same logic) I just get the error if I run it through the VS Code Debugger.
I still need to use the debugger tho'...any ideas on how to solve this situation??

**Comment by lamihck** [comment] 2019-04-03 15:50
Same here, I search somethink to solve this ...

**Comment by SteffenKohlhagen** [comment] 2019-05-02 13:27
v10.15.3

**Comment by jeromewu** [comment] 2019-05-10 04:27
@asWater 

Can you provide your the image you use?

BTW, you can also try the latest version of tesseract.js first by following command:

```
$ npm install tesseract.js@next
```

**Comment by asWater** [comment] 2019-05-10 09:11
Hi @jeromewu 

Thank you for your information.
As you suggested, I've upgraded the tesseract.js, and now the version is ^2.0.0-alpha.3.
After that, I've changed the code in order to make it adjust to the new version as follow.

const Tesseract = require( 'tesseract.js' ),
         { TesseractWorker } = Tesseract,
         worker = new TesseractWorker();

worker.recognize('http://jeroen.github.io/images/testocr.png')
	.progress( (p) => { console.log('progress', p); })
  	.then( (result) => { console.log('result', result); });

Now the error that I've reported previously (Channel closed ...) is disappeared.
However the console log does not show any progress and result.

Is something wrong with my code?
The picture and the code that I am using now is same with the example written in this github, so I believe that it must be right.

Could you please give me your advice again to overcome this problem?

**Comment by jeromewu** [comment] 2019-05-10 09:29
@asWater 

I try to run your code in my environment and it works as expected. Can you provide more information about your environment?

Like Operating System and so on.

Also can you try if you can successfully see the demo result in http://tesseract.projectnaptha.com/?

**Comment by asWater** [comment] 2019-05-10 10:20
Hi @jeromewu

My environment is as follow.
- OS: Windows 10
- Node: v10.15.1 (I'm using Nodist)

Now I am testing this Node application by using localhost.
i.e. 
1) Start the node application by using Visual Studio Code with the debugging mode.
2) Send the request to that node application by using Advanced REST Client
3) Node application uses tesseract by the code I've written before.

Currently I got the error as an attached screen.
It is strange but this error is not always shown.
Sometimes the applcation does not show anything, but sometimes it shows this error.
![image](https://user-images.githubusercontent.com/10876704/57520326-56145480-7358-11e9-9ee0-1553f98384b8.png)

Please give me your advice again.
And I you need more information, please let me know.

**Comment by jeromewu** [comment] 2019-05-10 10:55
Looks like you are using tesseract.js in a web server and trigger OCR by REST API.

I think the issue is caused by the fact that tesseract.js uses Node.js worker to do the recognition and somehow causes some issues. Do you use any frameworks like express.js?

Another possibility is that something worng with Node.js Windows version. In that case I suggest you to use cmd in Windows to execute the code above directly and check if it works.

**Comment by asWater** [comment] 2019-05-11 07:54
Hello @jeromewu 

Yes I am using the framework express.
As you suggested, I've executed the code by the command without using VS code debug mode, and it works and outputs the progress and result as expected.

The problem seems to be related with the usage of VS code, and it would not be the problem of tesseract, maybe.
However if you have any advice to overcome this issue, please let me know. I want to debug my code with using tesseract, should I use other debug methods?

If you don't have any advice for it, and you agree with that this issue is not related with tesseract anymore, please close this issue.

Thank you very much for your support.

**Comment by jeromewu** [comment] 2019-05-12 12:12
@asWater 

Sorry I don't have any experience in VS code and unable to help with this issue. Close the issue for now.

**Closed by jeromewu** 2019-05-12 12:12 UTC

**Comment by Patrick-Remy** [comment] 2019-08-21 15:33
Experiencing the same issue in combination of jest and debugging the unit tests...
