### ISSUE TITLE
Tesseract can't read the full image

### ISSUE THREAD

**Issue by TricksterCode210** [naptha/tesseract.js#777] opened 2023-06-05 07:59 UTC
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**
tesseract.js: 4.1.0
react: 18.2.0
npm: 8.5.0

**Describe the bug**
I'm doing my thesis about OCR scanners and I found this tesseract,js. I wanted to create some examples to my professor and I found this issue (or maybe I did not configure it that correctly). I think tesseract does not recognize the new paragraphs. I don't know how to configure it correctly or that's a bug, but I really need your help.
(Sorry if I was confusing)

**To Reproduce**
1. Choose the image to work with
2. Wait for the results

Please attach any input image required to replicate this behavior.
Result: 
![image](https://github.com/naptha/tesseract.js/assets/84982671/51b0ae67-0511-4c52-975e-0193fa513fd7)
Example image:
![image](https://github.com/naptha/tesseract.js/assets/84982671/be01d340-e111-4c83-9b27-54de3c7d724f)

**Expected behavior**
It should give me a huge text output

**Device Version:**
 - OS + Version: Windows 10
 - Browser edge
 - Node version node: v16.14.2

Code:
```
import { useEffect, useState } from "react";
import { createWorker } from "tesseract.js";
import "./App.css";
function App() {
  const [ocr, setOcr] = useState("");
  const [imageData, setImageData] = useState(null);
  const worker = createWorker({
    logger: (m) => {
      console.log(m);
    },
  });
  const convertImageToText = async () => {
    if (!imageData) return;
    await (await worker).load();
    await (await worker).loadLanguage("hun");
    await (await worker).initialize("hun");
    const {
      data: { text },
    } = await (await worker).recognize(imageData, {rotateAuto: true});
    setOcr(text);
  };

  useEffect(() => {
    convertImageToText();
  }, [imageData]);

  function handleImageChange(e) {
    const file = e.target.files[0];
    if(!file)return;
    const reader = new FileReader();
    reader.onloadend = () => {
      const imageDataUri = reader.result;
      console.log({ imageDataUri });
      setImageData(imageDataUri);
    };
    reader.readAsDataURL(file);
  }
  return (
      <div className="App">
        <div>
          <p>Choose an Image</p>
          <input
              type="file"
              name=""
              id=""
              onChange={handleImageChange}
              accept="image/*"
          />
        </div>
        <div className="display-flex">
          <img src={imageData} alt="" srcset="" />
          <p>{ocr}</p>
        </div>
      </div>
  );
}
export default App;
```

**Comment by Balearica** [comment] 2023-06-05 17:27
It looks like this is an issue with Tesseract rather than any code specific to Tesseract.js or your implementation. 

Tesseract uses a binarization algorithm provided by the Leptonica library by default (there are some configuration options related to binarization that you can look up in the Tesseract repo/documentation).  [This example](https://github.com/naptha/tesseract.js/blob/master/examples/browser/image-processing.html) shows how to access the intermediate images used by Tesseract.  For your image, the binarization algorithm performs extremely poorly with the text being almost entirely erased--I've attached the binarized image. 

![download (5)](https://github.com/naptha/tesseract.js/assets/100809261/a930e400-6525-43fd-b965-497737f26838)

I do not have a strong understanding of the Leptonica binarization algorithm bused by default, but the fact that the text is very light gray compared to some of the darker blacks found in the image appears to be what is tripping it up.  To demonstrate, removed the image, and the text no longer disappears during the binarization step. 

![user_example_1a](https://github.com/naptha/tesseract.js/assets/100809261/94c3bed6-ab80-4ea0-b41b-770b259d7157)
![download (6)](https://github.com/naptha/tesseract.js/assets/100809261/0b649fe8-2caf-47ae-914b-dfa9676d3264)

If you use the version with the image removed, Tesseract will spit out some text.  I do not expect it to be accurate--I can hardly make out the words in the input image personally, so do not expect Tesseract to be able to recognize it accurately. 

One final small thing--the `worker.load` function can be removed.  That was necessary in old versions but does not do anything in v4 and above.

**Comment by TricksterCode210** [comment] 2023-06-06 07:33
Thank you for your well explained answer. That helped me a lot.

**Comment by Balearica** [comment] 2023-06-06 22:43
No problem.  Closing the issue given this is not a bug with Tesseract.js.

**Closed by Balearica** 2023-06-06 22:43 UTC
Labels: recognition accuracy, Dependency Bug
