### ISSUE TITLE
Superfluous forward slash when loading trained data

### ISSUE THREAD

**Issue by TKone7** [naptha/tesseract.js#693] opened 2022-11-28 11:59 UTC
**Describe the bug**
When loading the trained.data file from my own domain, a superfluous forward slash is added to the request. 

**To Reproduce**
1. Create worker with option

```
  gzip: false,
  langPath: 'https://my-domain.com',
```

2. Load page and check for a `GET` request to download `xyz.trained-data`
3. Detected: `GET | https://my-domain.com//xyz-fast.traineddata`

**Expected behavior**
I would expect there to be only one forward slash:
`GET | https://my-domain.com/xyz-fast.traineddata`

**Desktop:**
 - OS: Linux
 - Browser: firefox
 - Version 107.0

**Additional Info**
It looks to me as if `resolve-url` is adding a forward slash when you resolve in-browser. Then another one is added when fetching the file.

**Comment by fmonpelat** [comment] 2022-12-07 19:06
Hi, i have the same issue and i can confirm that it doesn't load

**Comment by fmonpelat** [comment] 2022-12-07 23:54
I think that this line fixes the issue in `src/worker-script/index.js(line: 102)`:
```
path = langPath.replace(/\/$/, '');
```

**Comment by Balearica** [comment] 2022-12-08 01:04
@TKone7 @fmonpelat Thank you for reporting this issue and helping me understand.  I was confused why this hasn't come up before--it looks like it only happens when the path includes no subdirectory (either relative to the base URL for absolute paths or the current directory for relative paths).  

```
// These paths function as intended
resolveUrl("https://www.npmjs.com/package/lang")
'https://www.npmjs.com/package/lang'
resolveUrl("./lang")
'https://www.npmjs.com/package/lang'

// These paths have the bug you describe
resolveUrl("https://www.npmjs.com")
'https://www.npmjs.com/'
resolveUrl(".")
'https://www.npmjs.com/package/'
```

If anybody wants an extremely quick fix on their project, move your language data to a subdirectory.  Regarding resolving this bug, the fix proposed by @fmonpelat makes sense to me.  If you want to make a PR I will merge it in.  Otherwise I will edit this the next time I have a free time.

**Comment by fmonpelat** [comment] 2022-12-08 16:20
@Balearica i can make the pr, but i don't have permissions to upload a new branch

**Comment by Balearica** [comment] 2022-12-09 01:59
@fmonpelat Merged.  Thank you for your contribution.

**Closed by Balearica** 2022-12-09 01:59 UTC

**Comment by TKone7** [comment] 2022-12-12 10:55
Thank you all very much!
