### ISSUE TITLE
Uncaught Error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.

### ISSUE THREAD

**Issue by vodinhht20** [naptha/tesseract.js#849] opened 2023-10-30 02:52 UTC
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**

**Describe the bug**
Uncaught Error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.

**To Reproduce**
createWorker.js:173 Uncaught Error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at createWorker.js:173:1
    at worker.onmessage (onMessage.js:3:1)
    
    
    const worker = await createWorker({
          langPath: '...',
          logger: m => console.log(m),
      });
      await worker.load();
      console.log("language", language);
      await worker.loadLanguage(language);
      await worker.initialize(language);
      console.log("whileList", whileList);
      await worker.setParameters({
          tessedit_char_whitelist: whileList
      });
      const { data: { text } } = await worker.recognize(dataImag);

**Comment by Balearica** [comment] 2023-10-30 19:27
Please fill out the entire bug report issue template.  Notably, we have fields for both the Tesseract.js version number and the device/browser version, and you provided neither.

**Comment by Balearica** [comment] 2023-11-01 23:56
Closing.  We can reopen if the issue is edited to provide the necessary info.

**Closed by Balearica** 2023-11-01 23:56 UTC
