### ISSUE TITLE
Worker.initialize failed 

### ISSUE THREAD

**Issue by C0rentinC** [naptha/tesseract.js#793] opened 2023-06-29 19:02 UTC
**Tesseract.js version (version number for npm/GitHub release, or specific commit for repo)**
 "tesseract.js": "^4.0.2"

**Describe the bug**
I'm using Tesseract on a Discord Bot to read text on image and sometimes like 5% of time the bot is crashing, by debugging i finded Tesseract failed on the initialization.

Why the errorHandler of Tesseract do not catch the error? Is it a problem of traineddata ?

 It's been a while i try to found a solution but nothing yet.

I attach you an image with a case were the initialize failed and vice versa. And the code.

Thank you

Working 
![image](https://github.com/naptha/tesseract.js/assets/29143673/d6868a18-09cf-4378-8026-1f3d8c0e6560)
Crash
![image](https://github.com/naptha/tesseract.js/assets/29143673/794e4544-dc18-4d9f-b071-8a7182948ec2)

![image](https://github.com/naptha/tesseract.js/assets/29143673/fc529350-35c6-49dc-9387-2f51773e4cd3)

**Comment by Balearica** [comment] 2023-06-29 20:14
The only reason I can think of why initialization would fail in a non-deterministic manor is due to network issues. 

1. Update to the latest version (`v4.1.1` as of the time of this writing)
   1. There have been recent changes to reduce network issues, including (1) switching to a CDN with better reliability and (2) automatically deleting invalid language data downloads
1. If the issues continue, you can eliminate network-related issues by hosting all the necessary files locally
   1. How to host all files locally is explained [here](https://github.com/naptha/tesseract.js/blob/296afbcba624df26805b669b104780f7883ab4cf/docs/local-installation.md)

**Comment by CorentinCharriot** [comment] 2023-06-30 15:56
Thank you for your response, i have update to the last version i will see in the next days if the problem persist, if so i will try your second solution !

**Comment by Balearica** [comment] 2023-07-01 08:30
Okay, let me know what happens.  We are working to resolve these sorts of (seemingly) random/nondeterministic errors, however unfortunately as there are multiple causes and they are inherently difficult to replicate it can be difficult to know when a problem is fixed.

**Comment by CorentinCharriot** [comment] 2023-07-08 17:46
In 1 week i met this bug about 2 / 3 times

On this screen Tesseract failed to initialize
![image](https://github.com/naptha/tesseract.js/assets/29143673/bc64e02d-43c1-4bc1-aba2-bd488b186709)

And on this he seems failed at the beginning of the recognition, first time i encounter this
![image](https://github.com/naptha/tesseract.js/assets/29143673/658b3284-6e5f-4f9e-be7f-0837e4004f22)

I think its a network issue, i dont try to local install.

I just have to do that ?
`
const worker = await createWorker({
  workerPath: 'https://cdn.jsdelivr.net/npm/tesseract.js@v4.0.3/dist/worker.min.js',
  langPath: 'https://tessdata.projectnaptha.com/4.0.0',
  corePath: 'https://cdn.jsdelivr.net/npm/tesseract.js-core@v4.0.3',
});
`
Or just add `langPath`, im using Node.js

**Comment by Balearica** [comment] 2023-07-09 22:29
Does it fail repeatedly or does simply rerunning the failed command resolve the issue?  

Can you post a link to the code that you are running? 

I am now more skeptical that it is a network issue.  The Node.js version does not use a CDN for code (as all of the code is already in the npm package).  While the Node.js version does use a remote server for language data (which you can change to a local directory using `langPath`) your logs indicate that the language traineddata was loaded from the cache, which is (by definition) always local.

**Comment by CorentinCharriot** [comment] 2023-07-10 17:05
Just rerunning the command resolve the issue,

Actually the repo is private but this is the part of code were i use Tesseract: 
![image](https://github.com/naptha/tesseract.js/assets/29143673/13944f2f-ec2c-4175-8303-38e551bf8fa2)

But if you want i can send you more.

**Comment by Balearica** [comment] 2023-07-14 18:56
Is the code block you show above ever executed in parallel, with multiple images potentially being recognized at the same time?  Given that a worker is created and destroyed each time this is run, I could see this being problematic in a situations where that is the case.

**Comment by CorentinCharriot** [comment] 2023-07-17 01:48
No, this code is never executed in parellel and only with one image unfortunately :(

**Comment by Balearica** [comment] 2023-07-17 03:46
We've exhausted the obvious answers, so to go further we would need a reproducible example.  The snippet below is minimal code to run recognition 1,000 times in Node.js.  You can run it by cloning this repo, saving the snippet in the [examples ](https://github.com/naptha/tesseract.js/tree/master/examples/node) folder in a new file named `recognize_1000.js`, and then running `node recognize_1000.js [path to your file]` from within the examples directory on whatever system you are using for the bot.   

```
const path = require('path');
const { createWorker } = require('../../');

const [,, imagePath] = process.argv;
const image = path.resolve(__dirname, (imagePath || '../../tests/assets/images/cosmic.png'));

(async () => {
  for (let i=0; i<1e3; i++) {
    console.log("Starting iteration: " + i);
    console.log("Creating worker");
    const worker = await createWorker();  
    console.log("Loading language");
    await worker.loadLanguage('eng');
    console.log("Initializing");
    await worker.initialize('eng');
    console.log("Recognizing");
    const { data: { text } } = await worker.recognize(image);
    console.log("Terminating");
    await worker.terminate();
  }
})();
```

If you are unable to recognize a specific image 1,000 times in a row using this code, please provide the image so I can try and replicate.  If you are unable to produce an error using the code above with any image, then I think the issue is specific to some aspect of your project and not Tesseract.js.

**Comment by Balearica** [comment] 2023-07-25 19:25
Closing for now.  Will reopen is a reproducible example of code + image that causes these errors (even probabilistically/non-deterministically) is identified.

**Comment by Kumar6174** [comment] 2023-08-01 06:20
Tesseract.recognize(image);

i am passing image as blob data but  don't know why showing me href error
[TypeError: Cannot read property 'href' of undefined]

**Closed** 2023-08-04 02:05 UTC
