### ISSUE TITLE
Different result at different time for the same image in tesseract.js

### ISSUE THREAD

**Issue by VinilKumarReddy** [naptha/tesseract.js#503] opened 2020-12-08 14:52 UTC
We are getting coordinates of a specific part of the image and passing them to tesseract. tesseract will then extract information from the image passed as the parameter.
But the extracted text is different at different times for the same part of the image.

tesseract.js 0.7.3 is the version.

**Comment by Balearica** [comment] 2022-08-21 01:57
As adaptation/learning is enabled by default, it is possible (and indeed expected) that Tesseract's results change as you continue to use it, even for identical input data.  Let me know if this issue is still active and this behavior is problematic for a particular use case, and we can discuss options to disable.  Otherwise I will close the issue.

**Comment by Balearica** [comment] 2022-09-01 05:47
Closing as stale and not a bug.

**Closed by Balearica** 2022-09-01 05:47 UTC
