### ISSUE TITLE
Tesseractjs recognize Error: abort(undefined). Build with -s ASSERTIONS=1 for more info

### ISSUE THREAD

**Issue by hello-astar** [naptha/tesseract.js#441] opened 2020-04-23 03:22 UTC
**Using tesseractjs in vue-cli 3**
I use tesseractjs to recognize numbers with downloading language packages to local. 
After some tests, i got the runtime error `" abort(undefined). Build with -s ASSERTIONS=1 for more info "`. I dont't konw what happened as I restart the project ang ran tesseract  successfully.

**Steps**
1. start the project
2. dev_environment: (checked means performed well)
- [ ] recognize some images on mobile(access by ip address)
- [x] recognize some images on pc(access by localhost)
- [ ] recognize some images on pc(access by ip address)
4. see error - abort(undefingoued). Build with -s ASSERTIONS=1 for more info
5. all is well

**Expected behavior**
I want to know if this is a bug on Tesseractjs and what can I do to avoid the same situation.

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 78.0.3904.97

**Comment by zhanghouji** [comment] 2020-04-23 15:50
[https://github.com/zhanghouji/tesseract.js-issues](https://github.com/zhanghouji/tesseract.js-issues)

**Comment by jeromewu** [comment] 2020-04-26 06:32
Not sure about what happened as your description is pretty vague.

But you can try this offline example to see if the problem still exists: https://github.com/jeromewu/tesseract.js-offline

**Comment by liaoyiqing** [comment] 2020-09-22 00:04
make sure use port as 8000

**Comment by Sreekanthp74** [comment] 2021-01-12 16:20
Getting same error on Oracle Mobile Hub

 Error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at ChildProcess.onMessage (/u01/app/oracle/mobile/mobile_ccc/custom_code_modules/3aa4dac6-75eb-43c4-8086-86efa07ab658_46/bosexpensebackendapi/node_modules/tesseract.js/src/createWorker.js:173:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) 
    
    Is there any solution for this?

**Comment by Sreekanthp74** [comment] 2021-01-13 06:11
It is causing in the createWorker.js file
onMessage(worker, ({ workerId, jobId, status, action, data }) 

when data is undefined for the action initialize

**Comment by ngthuongdoan** [comment] 2021-03-16 11:24
Is this issue solved?  I tried a lot but it's still happening

**Comment by ylc395** [comment] 2021-11-19 15:39
I reproduced this error by passing an incorrect lang code as argument. So check your lang code.

**Comment by WahajAutoLeap** [comment] 2021-12-31 12:33
having same issue on IOS 15.2 was working fine on 15.1 and android

**Comment by mcanam** [comment] 2022-05-21 19:11
I also get the same error when using <eng> language but when using another language like <ind> it works fine

**Comment by tgraupmann** [comment] 2022-06-29 00:51
I'm seeing this error after running for about an hour or after processing 100+ images.

I tried trapping the error, but after an hour of processing, something is aborting recognition. A refresh of the browser continues normally. I'm setting images by reading the PNG file bytes and setting on the image source which I can see has loaded. when these errors are in the console.

One error before I added some error handling.

```
createWorker.js?73e0:173 Uncaught Error: RuntimeError: null function or function signature mismatch
    at eval (createWorker.js?73e0:173:1)
    at worker.onmessage (onMessage.js?7aa4:3:1)
eval @ createWorker.js?73e0:173
worker.onmessage @ onMessage.js?7aa4:3
asyncToGenerator.js?1da1:6 Uncaught (in promise) RuntimeError: null function or function signature mismatch
```

The error handling that I used.
```
process.on("uncaughtException", (err) => {
  if (!err) {
    console.error('process uncaughtException');
  } else {
    console.error('process uncaughtException stack', err.stack);
  }
});
```

This is the error that I'm getting with the error handling.

```
createWorker.js?73e0:173 Uncaught Error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at eval (createWorker.js?73e0:173:1)
    at worker.onmessage (onMessage.js?7aa4:3:1)
eval @ createWorker.js?73e0:173
worker.onmessage @ onMessage.js?7aa4:3
asyncToGenerator.js?1da1:6 Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
```

**Comment by Balearica** [comment] 2022-08-28 23:53
I'm closing this issue as `abort(undefined)` is an extremely generic error message with (as seen with the comments) many possible causes.  It's basically the equivalent of a "this program is not responding" error in a desktop application.  If anybody reading this encounters such an error, feel free to open a new issue with enough info to follow up (and ideally a reproducible example).

**Closed by Balearica** 2022-08-28 23:53 UTC

**Comment by duoluodexiaoxiaoyuan** [comment] 2022-11-25 06:54
i meet this problem,because you transforinto imagestream,  we must transerfor image addressi meet this problem,because you transforinto imagestream,  we must transerfor image address . in node.js environment.

in js brower , it's no problem
