### ISSUE TITLE
[npm warn]: resolve-url@0.2.1 is deprecated

### ISSUE THREAD

**Issue by MenaiAla** [naptha/tesseract.js#760] opened 2023-05-12 17:47 UTC
### Run command:

`npm install tesseract.js`

### Expected:

Installed package without **error** or **warning**.

### Current:

`npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated`

### Image:

![Screenshot from 2023-05-12 18-47-27](https://github.com/naptha/tesseract.js/assets/20143684/86c5aa6d-3e8f-4840-be42-791cb4f71bb3)

**Comment by Balearica** [comment] 2023-05-12 18:18
Duplicate of #725.

**Closed by Balearica** 2023-05-12 18:18 UTC
