### ISSUE TITLE
React native Error: ReferenceError: Can't find variable: document

### ISSUE THREAD

**Issue by dev932022** [naptha/tesseract.js#658] opened 2022-09-05 19:01 UTC
Hi!

I'm looking to do a basic test with React Native. But when I run it, I get the error:

  WARN Possible Unhandled Promise Rejection (id: 0):
ReferenceError: Can't find variable: document

This is my code

`import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

import Tesseract from "tesseract.js";
import { useEffect, useState } from 'react';

export default function App() {
  const doOCR = async () => {
    Tesseract.recognize('https://tesseract.projectnaptha.com/img/eng_bw.png', "eng", { logger: (m) => console.log(m) }).then(
      ({ data: { text } }) => {
        setOcr(text);
      }
    );
  };
  const [ocr, setOcr] = useState('Recognizing...');
  
  useEffect(() => {
    doOCR();
  });

  

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app! {ocr}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
`
And this is my package.json

{
  "name": "tesseract-rn-example",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "test": "jest",
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/webpack-config": "^0.17.2",
    "expo": "~46.0.9",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-native": "0.69.5",
    "react-native-web": "^0.18.9",
    "tesseract.js": "^3.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

**Comment by danyhiol** [comment] 2023-01-07 22:29
Same here: `ReferenceError: Can't find variable: document`. Only `tests`, `browser`, and `pdf` uses the document object. Is there any workaround for this? Or is TesseractJS simple not for react-native?
`"react-native": "0.70.5",`
`"expo-cli": "6.0.8",`
`"expo": "47.0.9",`

**Comment by Balearica** [comment] 2023-01-25 06:02
Closing as duplicate of #709.

**Closed by Balearica** 2023-01-25 06:02 UTC
